apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery
spec:
  replicas: 1  # Обычно 1 реплика для Beat
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: your-celery-image:latest  # Замените на образ вашего Celery
          command: ["celery", "-A", "project", "beat", "--loglevel=info"]  # Укажите вашу команду для запуска
          env:
            - name: REDIS_HOST
              value: "redis"  # Имя сервиса Redis в Kubernetes
            - name: OTHER_ENV_VARS
              valueFrom:
                secretKeyRef:
                  name: your-secret
                  key: your-key
