apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 3  # Количество реплик
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379  # Порт, на котором работает Redis
        volumeMounts:
        - name: redis-data
          mountPath: /data  # Путь, где будут храниться данные Redis
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc