# Generated by Django 5.1.2 on 2024-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track", models.BigIntegerField()),
                ("status", models.CharField(max_length=30)),
                ("message_type", models.IntegerField(default=0)),
                ("language", models.CharField(default="RUS", max_length=10)),
            ],
        ),
    ]
