# Generated by Django 5.1.2 on 2024-10-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackNumber',
            fields=[
                ('track', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='track_numbe_status_2791cf_idx')],
            },
        ),
    ]
