# Generated by Django 5.1.2 on 2024-10-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_number', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracknumber',
            name='message_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tracknumber',
            name='track',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
