# Generated by Django 5.1.2 on 2024-10-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_number', '0002_alter_tracknumber_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracknumber',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracknumber',
            name='track',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
