# Generated by Django 5.1.2 on 2024-10-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_number', '0003_remove_tracknumber_id_alter_tracknumber_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracknumber',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tracknumber',
            name='message_type',
        ),
        migrations.AddIndex(
            model_name='tracknumber',
            index=models.Index(fields=['status'], name='track_numbe_status_2791cf_idx'),
        ),
    ]
